// Defines the generation header.
export const header = "// This file was generated by arpc. Do not edit this file manually.\n";

// Defines the authentication import line.
export const authImport = 'import * as authentication from "./authentication";';

// Defines the rate limit import line.
export const rateLimitImport = 'import ratelimiting from "./ratelimiting";';
