name: "Handle @arpc-packages/core checks"

on:
    push:
        paths:
            - "packages/arpc-core/**"
            - ".github/workflows/core.yml"

jobs:
    node-test:
        name: "Run node tests (Node ${{ matrix.node-version }})"
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [18, 19, 20, 22, 23]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm ci
              working-directory: ./packages/arpc-core
            - run: npm run test
              working-directory: ./packages/arpc-core

    bun-test:
        name: "Run bun tests"
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: npm ci
              working-directory: ./packages/arpc-core
            - run: bun test
              working-directory: ./packages/arpc-core

    browser-test:
        name: "Run browser smoke test"
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
              working-directory: ./packages/arpc-core
            - name: Install playwright browsers
              run: npx playwright install --with-deps
              working-directory: ./packages/arpc-core
            - run: npm run smoke:browser
              working-directory: ./packages/arpc-core
